set_property SRC_FILE_INFO {cfile:C:/Users/l/Desktop/6463ADVHDes/code/project_12/project_12.srcs/constrs_1/new/top.xdc rfile:../../../project_12.srcs/constrs_1/new/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
NET "single"           LOC=N17 | IOSTANDARD=LVCMOS33; #IO_L9P_T1_DQS_14
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
NET "changecommit"           LOC=P18 | IOSTANDARD=LVCMOS33; #IO_L9N_T1_DQS_D13_14
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
NET "din_control"           LOC=P17 | IOSTANDARD=LVCMOS33; #IO_L12P_T1_MRCC_14
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
NET "changeAdd"           LOC=M17 | IOSTANDARD=LVCMOS33; #IO_L10N_T1_D15_14
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
NET "ukey_control"           LOC=M18 | IOSTANDARD=LVCMOS33; #IO_L4N_T0_D05_14
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
NET "key_rdy"         LOC=H17 | IOSTANDARD=LVCMOS33; #IO_L18P_T2_A24_15
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
NET "data_rdy"         LOC=K15 | IOSTANDARD=LVCMOS33; #IO_L24P_T3_RS1_15
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
NET "segA"             LOC=T10 | IOSTANDARD=LVCMOS33; #IO_L24N_T3_A00_D16_14
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
NET "segB"             LOC=R10 | IOSTANDARD=LVCMOS33; #IO_25_14
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
NET "segC"             LOC=K16 | IOSTANDARD=LVCMOS33; #IO_25_15
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
NET "segD"             LOC=K13 | IOSTANDARD=LVCMOS33; #IO_L17P_T2_A26_15
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
NET "segE"             LOC=P15 | IOSTANDARD=LVCMOS33; #IO_L13P_T2_MRCC_14
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
NET "segF"             LOC=T11 | IOSTANDARD=LVCMOS33; #IO_L19P_T3_A10_D26_14
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
NET "segG"             LOC=L18 | IOSTANDARD=LVCMOS33; #IO_L4P_T0_D04_14
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
NET "selectA"          LOC=J17 | IOSTANDARD=LVCMOS33; #IO_L23P_T3_FOE_B_15
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
NET "selectB"          LOC=J18 | IOSTANDARD=LVCMOS33; #IO_L23N_T3_FWE_B_15
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
NET "selectC"          LOC=T9 | IOSTANDARD=LVCMOS33; #IO_L24P_T3_A01_D17_14
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
NET "selectD"          LOC=J14 | IOSTANDARD=LVCMOS33; #IO_L19P_T3_A22_15
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
NET "selectE"          LOC=P14 | IOSTANDARD=LVCMOS33; #IO_L8N_T1_D12_14
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
NET "selectF"          LOC=T14 | IOSTANDARD=LVCMOS33; #IO_L14P_T2_SRCC_14
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
NET "selectG"          LOC=K2 | IOSTANDARD=LVCMOS33; #IO_L23P_T3_35
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
NET "selectH"          LOC=U13 | IOSTANDARD=LVCMOS33; #IO_L23N_T3_A02_D18_14
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {sw[0]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports {sw[1]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {sw[2]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {sw[3]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports {sw[4]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {sw[5]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {sw[6]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {sw[7]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {sw[8]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {sw[9]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {sw[10]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {sw[11]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {sw[12]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports {sw[13]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {sw[14]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {sw[15]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]
set_property src_info {type:XDC file:1 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports key_rdy]
set_property src_info {type:XDC file:1 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports data_rdy]
